// 單選逐題題庫（56 題）
// 每題 options 以 8 角色之一作為 role id：
// supporter / accumulator / landlord / technician / merchant / creator / star / matchmaker

export const QUESTIONS = [
  // ── 協作傾向 ─────────────────────────────────────────────
  { id: 'q1',  text: '遇到跨部門協作卡關時，你第一步會做什麼？', options: [
    { label: '先安撫情緒、釐清彼此期待', role: 'supporter' },
    { label: '列出阻塞點與資源清單', role: 'accumulator' },
    { label: '檢查制度/流程缺口', role: 'landlord' },
    { label: '重現問題並做技術驗證', role: 'technician' },
    { label: '尋找能交換的條件或商機', role: 'merchant' },
    { label: '用圖文把問題重新詮釋', role: 'creator' },
    { label: '召集會議，快速對齊結論', role: 'star' },
    { label: '找關鍵人拉線撮合解方', role: 'matchmaker' },
  ]},
  { id: 'q2',  text: '新人加入團隊，你會優先提供哪種協助？', options: [
    { label: '情緒支持與關係建立', role: 'supporter' },
    { label: 'SOP/資源地圖/帳號清單', role: 'accumulator' },
    { label: '系統權限與平台存取', role: 'landlord' },
    { label: '環境建置與工具安裝', role: 'technician' },
    { label: '介紹內部利害關係人與影響力地圖', role: 'merchant' },
    { label: '製作簡明入門教材', role: 'creator' },
    { label: '安排新人分享/破冰活動', role: 'star' },
    { label: '串起導師與跨組資源', role: 'matchmaker' },
  ]},
  { id: 'q3',  text: '你最喜歡的會議角色？', options: [
    { label: '紀錄與跟進', role: 'accumulator' },
    { label: '主持氣氛與控場', role: 'star' },
    { label: '技術把關', role: 'technician' },
    { label: '對外窗口/橋接人', role: 'matchmaker' },
    { label: '決策與拍板', role: 'landlord' },
    { label: '提案與說服', role: 'merchant' },
    { label: '同理與居中協調', role: 'supporter' },
    { label: '視覺化與簡報', role: 'creator' },
  ]},
  { id: 'q4',  text: '衝突升溫時你會？', options: [
    { label: '先緩和情緒，安排一對一', role: 'supporter' },
    { label: '回到事實表與紀錄', role: 'accumulator' },
    { label: '請權責單位定調', role: 'landlord' },
    { label: '驗證爭議點的數據與假設', role: 'technician' },
    { label: '找共同利益做交換', role: 'merchant' },
    { label: '換敘事框架與表達方式', role: 'creator' },
    { label: '讓大家快速投票表決', role: 'star' },
    { label: '引介第三方中立協調', role: 'matchmaker' },
  ]},

  // ── 產出與偏好 ───────────────────────────────────────────
  { id: 'q5',  text: '哪種工作讓你最有能量？', options: [
    { label: '幫人解決問題', role: 'supporter' },
    { label: '整理流程與檔案', role: 'accumulator' },
    { label: '建立制度與資產', role: 'landlord' },
    { label: '寫程式/修 bug/自動化', role: 'technician' },
    { label: '談合作/銷售/定價', role: 'merchant' },
    { label: '設計/寫作/做內容', role: 'creator' },
    { label: '演講/主持/露出', role: 'star' },
    { label: '牽線結合資源', role: 'matchmaker' },
  ]},
  { id: 'q6',  text: '被交付一個模糊的題目，你會先？', options: [
    { label: '訪談需求方，釐清痛點', role: 'supporter' },
    { label: '寫一份需求說明與範圍', role: 'accumulator' },
    { label: '盤點既有資產可重用', role: 'landlord' },
    { label: '做技術 spike/PoC', role: 'technician' },
    { label: '估算商業價值與成本', role: 'merchant' },
    { label: '做 wireframe/樣稿', role: 'creator' },
    { label: '找人共創快速發想', role: 'star' },
    { label: '找外部顧問或夥伴', role: 'matchmaker' },
  ]},
  { id: 'q7',  text: '完成一件事後你最在意？', options: [
    { label: '大家滿不滿意', role: 'supporter' },
    { label: '是否沉澱為 SOP', role: 'accumulator' },
    { label: '可否成為可複用資產', role: 'landlord' },
    { label: '品質與效能有沒有提升', role: 'technician' },
    { label: '對營收/轉化的影響', role: 'merchant' },
    { label: '內容與呈現是否到位', role: 'creator' },
    { label: '有沒有被看見', role: 'star' },
    { label: '是否擴大了人脈與合作', role: 'matchmaker' },
  ]},
  { id: 'q8',  text: '你最希望被如何形容？', options: [
    { label: '可靠、溫暖', role: 'supporter' },
    { label: '有條理、效率高', role: 'accumulator' },
    { label: '穩健、能托付', role: 'landlord' },
    { label: '專業、解難者', role: 'technician' },
    { label: '會做生意', role: 'merchant' },
    { label: '有品味、有創意', role: 'creator' },
    { label: '有影響力', role: 'star' },
    { label: '人脈王', role: 'matchmaker' },
  ]},

  // ── 商業與影響 ───────────────────────────────────────────
  { id: 'q9',  text: '如果多一個月資源，你會投在哪？', options: [
    { label: '客戶成功與社群', role: 'supporter' },
    { label: '內部工具與流程化', role: 'accumulator' },
    { label: '平台化/資產建設', role: 'landlord' },
    { label: '自動化與測試', role: 'technician' },
    { label: '銷售漏斗與廣告', role: 'merchant' },
    { label: '品牌內容與設計', role: 'creator' },
    { label: '公關/活動/曝光', role: 'star' },
    { label: '異業合作與渠道', role: 'matchmaker' },
  ]},
  { id: 'q10', text: '你評估專案成敗的主指標是？', options: [
    { label: '滿意度/留存', role: 'supporter' },
    { label: '里程碑準時率', role: 'accumulator' },
    { label: '可複用產物數', role: 'landlord' },
    { label: '故障率/效能', role: 'technician' },
    { label: '營收/轉化', role: 'merchant' },
    { label: '觸及/互動', role: 'creator' },
    { label: '曝光/提及', role: 'star' },
    { label: '合作數/渠道覆蓋', role: 'matchmaker' },
  ]},
  { id: 'q11', text: '你最認同的回饋是？', options: [
    { label: '服務超貼心', role: 'supporter' },
    { label: '條理超清楚', role: 'accumulator' },
    { label: '系統好穩/資產可用', role: 'landlord' },
    { label: '技術很硬', role: 'technician' },
    { label: '很會談/會賣', role: 'merchant' },
    { label: '超好看/內容精彩', role: 'creator' },
    { label: '好會講/帶氛圍', role: 'star' },
    { label: '人脈好廣', role: 'matchmaker' },
  ]},
  { id: 'q12', text: '遇到模糊的 KPI，你最會？', options: [
    { label: '把質性回饋轉為行動', role: 'supporter' },
    { label: '寫出衡量表與節奏', role: 'accumulator' },
    { label: '沉澱長期資產指標', role: 'landlord' },
    { label: '加上技術監測與報表', role: 'technician' },
    { label: '換成商業可驗證假設', role: 'merchant' },
    { label: '把指標視覺化/敘事', role: 'creator' },
    { label: '以公開檢視提升動能', role: 'star' },
    { label: '找外部標竿與合作指標', role: 'matchmaker' },
  ]},

  // ── 流程與習慣 ───────────────────────────────────────────
  { id: 'q13', text: '你每天最固定的一件事？', options: [
    { label: '回覆訊息與關懷', role: 'supporter' },
    { label: '整理待辦與清單', role: 'accumulator' },
    { label: '檢查資產與權限', role: 'landlord' },
    { label: '讀 log/優化腳本', role: 'technician' },
    { label: '追蹤漏斗與指標', role: 'merchant' },
    { label: '產出/改稿', role: 'creator' },
    { label: '發社群/分享', role: 'star' },
    { label: '約咖啡/維繫人脈', role: 'matchmaker' },
  ]},
  { id: 'q14', text: '你最常建立哪種文件？', options: [
    { label: 'FAQ/回覆範本', role: 'supporter' },
    { label: 'SOP/流程圖', role: 'accumulator' },
    { label: '資產清單/角色與權限表', role: 'landlord' },
    { label: 'Runbook/技術手冊', role: 'technician' },
    { label: '商機名單/報價單', role: 'merchant' },
    { label: '版型/品牌指南', role: 'creator' },
    { label: '簡報/講稿', role: 'star' },
    { label: '夥伴合作企劃', role: 'matchmaker' },
  ]},
  { id: 'q15', text: '時間不夠時你會先做？', options: [
    { label: '處理別人的緊急需求', role: 'supporter' },
    { label: '關鍵里程碑', role: 'accumulator' },
    { label: '長期價值產出', role: 'landlord' },
    { label: '風險最大/技術難點', role: 'technician' },
    { label: '最接近營收的事', role: 'merchant' },
    { label: '最能展示成果的事', role: 'creator' },
    { label: '最能曝光的事', role: 'star' },
    { label: '最能拉資源的事', role: 'matchmaker' },
  ]},
  { id: 'q16', text: '你對會議的堅持是？', options: [
    { label: '讓每個人都被聽見', role: 'supporter' },
    { label: '議程與紀錄完整', role: 'accumulator' },
    { label: '明確負責與時程', role: 'landlord' },
    { label: '可操作的技術下一步', role: 'technician' },
    { label: '結論能推動合作/交易', role: 'merchant' },
    { label: '輸出可公開的素材', role: 'creator' },
    { label: '節奏緊湊、時間管理', role: 'star' },
    { label: '找出關鍵利害關係人', role: 'matchmaker' },
  ]},

  // ── 內容/設計/表達 ────────────────────────────────────────
  { id: 'q17', text: '你做簡報最重視？', options: [
    { label: '觀眾感受與互動', role: 'supporter' },
    { label: '結構清楚層次分明', role: 'accumulator' },
    { label: '決策所需與權責清楚', role: 'landlord' },
    { label: '技術細節與可行性', role: 'technician' },
    { label: '商業價值與轉化', role: 'merchant' },
    { label: '版面美感與敘事', role: 'creator' },
    { label: '舞台表現與節奏', role: 'star' },
    { label: '故事中植入關鍵關係', role: 'matchmaker' },
  ]},
  { id: 'q18', text: '你偏好的內容形式？', options: [
    { label: '客服知識庫/指南', role: 'supporter' },
    { label: '操作手冊/清單', role: 'accumulator' },
    { label: '資產圖譜/系統地圖', role: 'landlord' },
    { label: '技術文章/範例程式', role: 'technician' },
    { label: '案例/ROI 報告', role: 'merchant' },
    { label: '視覺設計/短片', role: 'creator' },
    { label: '演講/直播', role: 'star' },
    { label: '專訪/對談', role: 'matchmaker' },
  ]},
  { id: 'q19', text: '若要擴散成果，你會先？', options: [
    { label: '寫成功故事讓用戶發聲', role: 'supporter' },
    { label: '整理成操作包可複用', role: 'accumulator' },
    { label: '做平台頁/資產化', role: 'landlord' },
    { label: '開源/技術分享', role: 'technician' },
    { label: '投放廣告/寄信名單', role: 'merchant' },
    { label: '做成資訊圖/短影音', role: 'creator' },
    { label: '辦分享會/上台', role: 'star' },
    { label: '找 KOL/夥伴聯名', role: 'matchmaker' },
  ]},
  { id: 'q20', text: '你對設計的看法最接近？', options: [
    { label: '讓人感到被理解', role: 'supporter' },
    { label: '降低認知負荷', role: 'accumulator' },
    { label: '形成長期品牌資產', role: 'landlord' },
    { label: '可維護、可擴展', role: 'technician' },
    { label: '提升轉化與商業價值', role: 'merchant' },
    { label: '故事與審美體驗', role: 'creator' },
    { label: '舞台化與記憶點', role: 'star' },
    { label: '社會化與共創', role: 'matchmaker' },
  ]},

  // ── 技術/系統/平台 ────────────────────────────────────────
  { id: 'q21', text: '工具選型你會先看？', options: [
    { label: '對使用者友好', role: 'supporter' },
    { label: '流程串接與文檔', role: 'accumulator' },
    { label: '權限/租戶/資產模式', role: 'landlord' },
    { label: '效能/穩定/社群', role: 'technician' },
    { label: '商業授權與成本', role: 'merchant' },
    { label: '可輸出品牌體驗', role: 'creator' },
    { label: '展示/匯報容易', role: 'star' },
    { label: '與外部合作相容', role: 'matchmaker' },
  ]},
  { id: 'q22', text: '你最想優化哪一項？', options: [
    { label: '客服回覆速度/滿意度', role: 'supporter' },
    { label: '任務流與自動化', role: 'accumulator' },
    { label: '資產盤點與權責', role: 'landlord' },
    { label: '監控與可觀測性', role: 'technician' },
    { label: '漏斗每一步轉化率', role: 'merchant' },
    { label: '設計系統與元件庫', role: 'creator' },
    { label: '簡報模板與說明書', role: 'star' },
    { label: '夥伴流程/分潤機制', role: 'matchmaker' },
  ]},
  { id: 'q23', text: '交付前最後一關你會看？', options: [
    { label: '使用指導/客服腳本', role: 'supporter' },
    { label: '檢核表/風險清單', role: 'accumulator' },
    { label: '權限與資料落地', role: 'landlord' },
    { label: '測試報告/覆蓋率', role: 'technician' },
    { label: '定價與包裝', role: 'merchant' },
    { label: '體驗細節/文案', role: 'creator' },
    { label: '發布節奏/宣傳檔', role: 'star' },
    { label: '通路上架/合作協議', role: 'matchmaker' },
  ]},
  { id: 'q24', text: '維運事故你會？', options: [
    { label: '主動安撫用戶並同步狀態', role: 'supporter' },
    { label: '建立事後檢討文件', role: 'accumulator' },
    { label: '調整制度與權責邊界', role: 'landlord' },
    { label: '快修與根因分析', role: 'technician' },
    { label: '評估商業損失與補償', role: 'merchant' },
    { label: '做可理解的事故報告', role: 'creator' },
    { label: '公開透明對外說明', role: 'star' },
    { label: '引入外部資源協助', role: 'matchmaker' },
  ]},

  // ── 人際/領導/成長 ────────────────────────────────────────
  { id: 'q25', text: '你帶人的風格是？', options: [
    { label: '同理陪跑', role: 'supporter' },
    { label: '任務與節奏管理', role: 'accumulator' },
    { label: '授權與制度化', role: 'landlord' },
    { label: '技術指導與 code review', role: 'technician' },
    { label: '以目標/獎酬驅動', role: 'merchant' },
    { label: '示範與手把手教學', role: 'creator' },
    { label: '鼓舞與激勵', role: 'star' },
    { label: '讓人連結到資源', role: 'matchmaker' },
  ]},
  { id: 'q26', text: '加入新團隊你會先建立？', options: [
    { label: '使用者訪談機制', role: 'supporter' },
    { label: '專案節奏與儀表板', role: 'accumulator' },
    { label: '資產與權限規範', role: 'landlord' },
    { label: '技術標準/模板', role: 'technician' },
    { label: '商機/客戶資料庫', role: 'merchant' },
    { label: '品牌/設計系統', role: 'creator' },
    { label: '對外展示方案', role: 'star' },
    { label: '合作夥伴名冊', role: 'matchmaker' },
  ]},
  { id: 'q27', text: '你最想被安排的職務挑戰？', options: [
    { label: '用戶成功/社群經營', role: 'supporter' },
    { label: 'PMO/流程改造', role: 'accumulator' },
    { label: '平台/產品負責人', role: 'landlord' },
    { label: 'Tech Lead/架構師', role: 'technician' },
    { label: 'BD/Sales Lead', role: 'merchant' },
    { label: '內容/品牌主理', role: 'creator' },
    { label: '公關/活動主理', role: 'star' },
    { label: '策略合作負責人', role: 'matchmaker' },
  ]},
  { id: 'q28', text: '你覺得最有價值的學習是？', options: [
    { label: '共情與提問技巧', role: 'supporter' },
    { label: '系統化/時間管理', role: 'accumulator' },
    { label: '資產思維/商業模式', role: 'landlord' },
    { label: '底層技術與原理', role: 'technician' },
    { label: '談判/定價/銷售', role: 'merchant' },
    { label: '美學/敘事/框架', role: 'creator' },
    { label: '表達/主持/說服', role: 'star' },
    { label: '網絡/社會資本', role: 'matchmaker' },
  ]},

  // ── 情境題（職場日常） ────────────────────────────────────
  { id: 'q29', text: '上線前一天發現文案錯字，你會？', options: [
    { label: '先通知對外窗口以安撫', role: 'supporter' },
    { label: '開 PR 並更新 checklist', role: 'accumulator' },
    { label: '檢查權限避免再次發生', role: 'landlord' },
    { label: '修正並補測', role: 'technician' },
    { label: '同步影響對營收的頁面', role: 'merchant' },
    { label: '同時優化可讀性', role: 'creator' },
    { label: '公告修正資訊', role: 'star' },
    { label: '請夥伴協助加速審稿', role: 'matchmaker' },
  ]},
  { id: 'q30', text: 'KPI 落後 20%，你會先？', options: [
    { label: '蒐集使用者阻礙', role: 'supporter' },
    { label: '拆里程碑找瓶頸', role: 'accumulator' },
    { label: '調整資源與優先級', role: 'landlord' },
    { label: '壓關鍵技術改動', role: 'technician' },
    { label: '做促銷/調整定價', role: 'merchant' },
    { label: '改版關鍵頁面', role: 'creator' },
    { label: '強化對外溝通節奏', role: 'star' },
    { label: '開發新合作渠道', role: 'matchmaker' },
  ]},
  { id: 'q31', text: '跨國合作時差大，你會？', options: [
    { label: '建立非同步溝通規則', role: 'supporter' },
    { label: '統一文件與任務板', role: 'accumulator' },
    { label: '設定權限與流程關卡', role: 'landlord' },
    { label: '以自動化腳本串流程', role: 'technician' },
    { label: '以 SLA 與合約管理', role: 'merchant' },
    { label: '準備圖像化溝通材料', role: 'creator' },
    { label: '固定節奏全員同步', role: 'star' },
    { label: '指定區域協調人', role: 'matchmaker' },
  ]},
  { id: 'q32', text: '有兩個好點子但只能做一個，你偏向？', options: [
    { label: '選對用戶最友善的', role: 'supporter' },
    { label: '選資源效率最高的', role: 'accumulator' },
    { label: '選能沉澱資產的', role: 'landlord' },
    { label: '選技術風險最低的', role: 'technician' },
    { label: '選商業價值最高的', role: 'merchant' },
    { label: '選最能展示質感的', role: 'creator' },
    { label: '選最能帶動聲量的', role: 'star' },
    { label: '選能打開合作大門的', role: 'matchmaker' },
  ]},

  // ── 自我定位 ─────────────────────────────────────────────
  { id: 'q33', text: '你更像哪種夥伴？', options: [
    { label: '治癒系', role: 'supporter' },
    { label: '整理控', role: 'accumulator' },
    { label: '管家型', role: 'landlord' },
    { label: '修復者', role: 'technician' },
    { label: '成交王', role: 'merchant' },
    { label: '靈感機', role: 'creator' },
    { label: '發電機', role: 'star' },
    { label: '連接器', role: 'matchmaker' },
  ]},
  { id: 'q34', text: '如果讓你當一天主管，你會先改什麼？', options: [
    { label: '回饋與關懷機制', role: 'supporter' },
    { label: '專案看板與節奏', role: 'accumulator' },
    { label: '權限與責任分工', role: 'landlord' },
    { label: '工程標準與自動化', role: 'technician' },
    { label: '獎酬與目標制度', role: 'merchant' },
    { label: '品牌與視覺體驗', role: 'creator' },
    { label: '例會節奏與文化', role: 'star' },
    { label: '外部合作策略', role: 'matchmaker' },
  ]},
  { id: 'q35', text: '在你眼中最稀缺的是？', options: [
    { label: '信任與關係', role: 'supporter' },
    { label: '時間與秩序', role: 'accumulator' },
    { label: '可持續的資產', role: 'landlord' },
    { label: '可靠的系統', role: 'technician' },
    { label: '可複製的成交方法', role: 'merchant' },
    { label: '優秀的內容與設計', role: 'creator' },
    { label: '注意力與影響力', role: 'star' },
    { label: '可動員的網絡', role: 'matchmaker' },
  ]},
  { id: 'q36', text: '你對「成功」的定義？', options: [
    { label: '讓更多人被看見與被幫助', role: 'supporter' },
    { label: '讓團隊有秩序且持續進步', role: 'accumulator' },
    { label: '建立能自轉的系統', role: 'landlord' },
    { label: '把難題變簡單', role: 'technician' },
    { label: '創造穩定現金流', role: 'merchant' },
    { label: '產出能被傳頌的作品', role: 'creator' },
    { label: '影響更多人採取行動', role: 'star' },
    { label: '讓資源在對的人手上', role: 'matchmaker' },
  ]},

  // ── 領域情境延伸（工程/內容/商務/營運） ────────────────
  { id: 'q37', text: '工程專案 kickoff 時你會？', options: [
    { label: '先盤點使用者情境', role: 'supporter' },
    { label: '拆任務與排期', role: 'accumulator' },
    { label: '定資料權限與治理', role: 'landlord' },
    { label: '技術選型與 spike', role: 'technician' },
    { label: '估效益與成本', role: 'merchant' },
    { label: '設計 API/文件風格', role: 'creator' },
    { label: '安排定期 demo', role: 'star' },
    { label: '引介外部技術夥伴', role: 'matchmaker' },
  ]},
  { id: 'q38', text: '內容專案最先做？', options: [
    { label: '用戶研究/同理地圖', role: 'supporter' },
    { label: '建立內容日曆/流程', role: 'accumulator' },
    { label: '版型庫與授權機制', role: 'landlord' },
    { label: '製作/剪輯流程最佳化', role: 'technician' },
    { label: '商業目標/KPIs', role: 'merchant' },
    { label: '敘事與視覺語言', role: 'creator' },
    { label: '發佈節奏/社群', role: 'star' },
    { label: '跨平台/聯名合作', role: 'matchmaker' },
  ]},
  { id: 'q39', text: '商務談判你最在意？', options: [
    { label: '雙方關係與信任', role: 'supporter' },
    { label: '條款細節與交付', role: 'accumulator' },
    { label: '風險與資產保護', role: 'landlord' },
    { label: '技術可行與範圍', role: 'technician' },
    { label: '價格與付款條件', role: 'merchant' },
    { label: '提案與包裝', role: 'creator' },
    { label: '會議節奏與窗口', role: 'star' },
    { label: '導入外部資源換條件', role: 'matchmaker' },
  ]},
  { id: 'q40', text: '營運日常你會把力氣放在？', options: [
    { label: '客服與社群溝通', role: 'supporter' },
    { label: '儀表板與例會節奏', role: 'accumulator' },
    { label: '資產維護與授權', role: 'landlord' },
    { label: '自動化與排程', role: 'technician' },
    { label: '活動/促案/名單', role: 'merchant' },
    { label: '內容再利用', role: 'creator' },
    { label: '活動曝光', role: 'star' },
    { label: '通路/代理商管理', role: 'matchmaker' },
  ]},

  // ── 價值觀與偏好（補齊題量） ────────────────────────────
  { id: 'q41', text: '你心中的好團隊特質？', options: [
    { label: '互助與信任', role: 'supporter' },
    { label: '有節奏與秩序', role: 'accumulator' },
    { label: '穩健可持續', role: 'landlord' },
    { label: '專業可靠', role: 'technician' },
    { label: '目標導向', role: 'merchant' },
    { label: '審美與品味', role: 'creator' },
    { label: '活力與氣氛', role: 'star' },
    { label: '對外連結強', role: 'matchmaker' },
  ]},
  { id: 'q42', text: '你最不喜歡的狀況？', options: [
    { label: '冷漠與漠視', role: 'supporter' },
    { label: '混亂與遲到', role: 'accumulator' },
    { label: '權責不清', role: 'landlord' },
    { label: '草率與不專業', role: 'technician' },
    { label: '沒有目標', role: 'merchant' },
    { label: '醜與難懂', role: 'creator' },
    { label: '沒人發言', role: 'star' },
    { label: '封閉無合作', role: 'matchmaker' },
  ]},
  { id: 'q43', text: '若可多一技能，你選？', options: [
    { label: '助人對話術', role: 'supporter' },
    { label: '流程設計', role: 'accumulator' },
    { label: '商業/法務基礎', role: 'landlord' },
    { label: 'DevOps/自動化', role: 'technician' },
    { label: '談判成交', role: 'merchant' },
    { label: '影像/設計', role: 'creator' },
    { label: '演說主持', role: 'star' },
    { label: '關係經營', role: 'matchmaker' },
  ]},
  { id: 'q44', text: '你最欣賞哪種同事？', options: [
    { label: '總是願意幫忙', role: 'supporter' },
    { label: '把事情變簡單', role: 'accumulator' },
    { label: '替團隊背責任', role: 'landlord' },
    { label: '技術超可靠', role: 'technician' },
    { label: '能把價值變現', role: 'merchant' },
    { label: '把抽象變具象', role: 'creator' },
    { label: '能帶動大家', role: 'star' },
    { label: '總能找到資源', role: 'matchmaker' },
  ]},

  // ── 決策/風險/資源 ────────────────────────────────────────
  { id: 'q45', text: '面對風險，你習慣？', options: [
    { label: '人際預防線', role: 'supporter' },
    { label: '風險矩陣與應對', role: 'accumulator' },
    { label: '制度與合約', role: 'landlord' },
    { label: '技術 fallback', role: 'technician' },
    { label: '轉嫁/對價', role: 'merchant' },
    { label: '溝通設計', role: 'creator' },
    { label: '即時溝通與揭露', role: 'star' },
    { label: '引進外援', role: 'matchmaker' },
  ]},
  { id: 'q46', text: '資源不足時你的策略？', options: [
    { label: '優先服務影響最大的人', role: 'supporter' },
    { label: '縮小範圍但完成閉環', role: 'accumulator' },
    { label: '聚焦可沉澱資產之處', role: 'landlord' },
    { label: '技術簡化/重用', role: 'technician' },
    { label: '找變現最快的路徑', role: 'merchant' },
    { label: '以視覺敘事放大成果', role: 'creator' },
    { label: '以儀式感提高動能', role: 'star' },
    { label: '借力打力/合作', role: 'matchmaker' },
  ]},
  { id: 'q47', text: '你最樂於分享的是？', options: [
    { label: '經驗與同理', role: 'supporter' },
    { label: '模版/清單', role: 'accumulator' },
    { label: '資源與平台', role: 'landlord' },
    { label: '技術與工具', role: 'technician' },
    { label: '商機與渠道', role: 'merchant' },
    { label: '靈感與作品', role: 'creator' },
    { label: '舞台與麥克風', role: 'star' },
    { label: '人脈與連結', role: 'matchmaker' },
  ]},
  { id: 'q48', text: '你最希望被分配的 KPI？', options: [
    { label: 'NPS/CSAT', role: 'supporter' },
    { label: 'SLA/準時率', role: 'accumulator' },
    { label: '資產覆蓋度', role: 'landlord' },
    { label: 'MTTR/可用性', role: 'technician' },
    { label: 'MRR/CVR', role: 'merchant' },
    { label: '曝光/互動率', role: 'creator' },
    { label: '活動參與度', role: 'star' },
    { label: '合作數/貢獻度', role: 'matchmaker' },
  ]},

  // ── 收尾補充題（到 56 題） ────────────────────────────────
  { id: 'q49', text: '做決策時最需要的資訊？', options: [
    { label: '使用者聲音', role: 'supporter' },
    { label: '數據與里程碑', role: 'accumulator' },
    { label: '資產/成本/權責', role: 'landlord' },
    { label: '技術可行性', role: 'technician' },
    { label: '商業效益', role: 'merchant' },
    { label: '敘事與呈現', role: 'creator' },
    { label: '時機與氛圍', role: 'star' },
    { label: '關係與盟友', role: 'matchmaker' },
  ]},
  { id: 'q50', text: '若只能選一個副專長，你會補？', options: [
    { label: '教練式對話', role: 'supporter' },
    { label: '專案管理', role: 'accumulator' },
    { label: '資產規劃', role: 'landlord' },
    { label: '雲端/自動化', role: 'technician' },
    { label: '行銷/銷售', role: 'merchant' },
    { label: '品牌/設計', role: 'creator' },
    { label: '溝通/主持', role: 'star' },
    { label: '關係經營', role: 'matchmaker' },
  ]},
  { id: 'q51', text: '哪種讚美讓你有動力？', options: [
    { label: '你讓我很踏實', role: 'supporter' },
    { label: '你把複雜變簡單', role: 'accumulator' },
    { label: '交給你我放心', role: 'landlord' },
    { label: '你超可靠', role: 'technician' },
    { label: '你很會抓價值', role: 'merchant' },
    { label: '好美/好懂', role: 'creator' },
    { label: '你很會帶風向', role: 'star' },
    { label: '你人脈好強', role: 'matchmaker' },
  ]},
  { id: 'q52', text: '你最常用哪種工具？', options: [
    { label: '客服/表單', role: 'supporter' },
    { label: '看板/Notion', role: 'accumulator' },
    { label: 'Drive/權限管理', role: 'landlord' },
    { label: 'CLI/監控', role: 'technician' },
    { label: 'CRM/GA4', role: 'merchant' },
    { label: 'Figma/剪輯', role: 'creator' },
    { label: 'Slides/直播', role: 'star' },
    { label: 'LinkedIn/名單', role: 'matchmaker' },
  ]},
  { id: 'q53', text: '對新事物你的反應？', options: [
    { label: '先了解對人有何幫助', role: 'supporter' },
    { label: '看流程是否能改善', role: 'accumulator' },
    { label: '想是否能變資產', role: 'landlord' },
    { label: '試測技術成熟度', role: 'technician' },
    { label: '評估變現機會', role: 'merchant' },
    { label: '想像能否說好故事', role: 'creator' },
    { label: '思考可如何曝光', role: 'star' },
    { label: '找誰能一起玩', role: 'matchmaker' },
  ]},
  { id: 'q54', text: '專案尾聲你會做？', options: [
    { label: '感謝名單與回饋', role: 'supporter' },
    { label: '復盤文件與改進點', role: 'accumulator' },
    { label: '資產化/授權整理', role: 'landlord' },
    { label: '技術債與優化路線', role: 'technician' },
    { label: '案例包/證言', role: 'merchant' },
    { label: '亮點集/作品集', role: 'creator' },
    { label: '對外分享/發佈', role: 'star' },
    { label: '延伸合作清單', role: 'matchmaker' },
  ]},
  { id: 'q55', text: '你最擅長的溝通方式？', options: [
    { label: '傾聽與共感', role: 'supporter' },
    { label: '結構化與文件', role: 'accumulator' },
    { label: '就事論事定規則', role: 'landlord' },
    { label: '用數據與實驗', role: 'technician' },
    { label: '以利益交換', role: 'merchant' },
    { label: '用圖像講故事', role: 'creator' },
    { label: '現場帶動', role: 'star' },
    { label: '撮合雙方', role: 'matchmaker' },
  ]},
  { id: 'q56', text: '如果只留一種輸出，你會選？', options: [
    { label: '服務體驗', role: 'supporter' },
    { label: '流程與模板', role: 'accumulator' },
    { label: '平台與資產', role: 'landlord' },
    { label: '穩健的系統', role: 'technician' },
    { label: '現金流', role: 'merchant' },
    { label: '作品', role: 'creator' },
    { label: '影響力', role: 'star' },
    { label: '網絡', role: 'matchmaker' },
  ]},
]
